TRUNCATE TABLE transactions CASCADE;
TRUNCATE TABLE import_logs CASCADE;
TRUNCATE TABLE reconciliations CASCADE;
TRUNCATE TABLE patio_os CASCADE;
TRUNCATE TABLE recebiveis CASCADE;
TRUNCATE TABLE daily_snapshots CASCADE;
