events {}

http {
  server {
    listen 80;

    location /api/orquestrador/ {
      proxy_pass http://orquestrador:8080/;
      proxy_set_header Host $host;
    }

    location /api/agent-runtime/ {
      proxy_pass http://agent-runtime:8081/;
      proxy_set_header Host $host;
    }

    location /api/integration-hub/ {
      proxy_pass http://integration-hub:8082/;
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://orquestrador:8080/;
      proxy_set_header Host $host;
    }
  }
}
