/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecebiveisRouteImport } from './routes/recebiveis'
import { Route as PropostaRouteImport } from './routes/proposta'
import { Route as PatioRouteImport } from './routes/patio'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportarOsRouteImport } from './routes/importar-os'
import { Route as ImportacoesDespesasRouteImport } from './routes/importacoes-despesas'
import { Route as ImportacoesRouteImport } from './routes/importacoes'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as CustosRouteImport } from './routes/custos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConciliacaoDetalhesRouteImport } from './routes/conciliacao-detalhes'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AgenteRouteImport } from './routes/agente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConciliacaoIndexRouteImport } from './routes/conciliacao.index'
import { Route as LojaLojaIdRouteImport } from './routes/loja.$lojaId'
import { Route as LogsMotorRouteImport } from './routes/logs.motor'
import { Route as LogsAgenteRouteImport } from './routes/logs.agente'
import { Route as ConciliacaoLojaIdRouteImport } from './routes/conciliacao.$lojaId'

const RecebiveisRoute = RecebiveisRouteImport.update({
  id: '/recebiveis',
  path: '/recebiveis',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaRoute = PropostaRouteImport.update({
  id: '/proposta',
  path: '/proposta',
  getParentRoute: () => rootRouteImport,
} as any)
const PatioRoute = PatioRouteImport.update({
  id: '/patio',
  path: '/patio',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarOsRoute = ImportarOsRouteImport.update({
  id: '/importar-os',
  path: '/importar-os',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesDespesasRoute = ImportacoesDespesasRouteImport.update({
  id: '/importacoes-despesas',
  path: '/importacoes-despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesRoute = ImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosRoute = CustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoDetalhesRoute = ConciliacaoDetalhesRouteImport.update({
  id: '/conciliacao-detalhes',
  path: '/conciliacao-detalhes',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteRoute = AgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoIndexRoute = ConciliacaoIndexRouteImport.update({
  id: '/conciliacao/',
  path: '/conciliacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaLojaIdRoute = LojaLojaIdRouteImport.update({
  id: '/loja/$lojaId',
  path: '/loja/$lojaId',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsMotorRoute = LogsMotorRouteImport.update({
  id: '/logs/motor',
  path: '/logs/motor',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsAgenteRoute = LogsAgenteRouteImport.update({
  id: '/logs/agente',
  path: '/logs/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoLojaIdRoute = ConciliacaoLojaIdRouteImport.update({
  id: '/conciliacao/$lojaId',
  path: '/conciliacao/$lojaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/alertas': typeof AlertasRoute
  '/bootstrap': typeof BootstrapRoute
  '/conciliacao-detalhes': typeof ConciliacaoDetalhesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/historico': typeof HistoricoRoute
  '/importacoes': typeof ImportacoesRoute
  '/importacoes-despesas': typeof ImportacoesDespesasRoute
  '/importar-os': typeof ImportarOsRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRoute
  '/patio': typeof PatioRoute
  '/proposta': typeof PropostaRoute
  '/recebiveis': typeof RecebiveisRoute
  '/conciliacao/$lojaId': typeof ConciliacaoLojaIdRoute
  '/logs/agente': typeof LogsAgenteRoute
  '/logs/motor': typeof LogsMotorRoute
  '/loja/$lojaId': typeof LojaLojaIdRoute
  '/conciliacao/': typeof ConciliacaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/alertas': typeof AlertasRoute
  '/bootstrap': typeof BootstrapRoute
  '/conciliacao-detalhes': typeof ConciliacaoDetalhesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/historico': typeof HistoricoRoute
  '/importacoes': typeof ImportacoesRoute
  '/importacoes-despesas': typeof ImportacoesDespesasRoute
  '/importar-os': typeof ImportarOsRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRoute
  '/patio': typeof PatioRoute
  '/proposta': typeof PropostaRoute
  '/recebiveis': typeof RecebiveisRoute
  '/conciliacao/$lojaId': typeof ConciliacaoLojaIdRoute
  '/logs/agente': typeof LogsAgenteRoute
  '/logs/motor': typeof LogsMotorRoute
  '/loja/$lojaId': typeof LojaLojaIdRoute
  '/conciliacao': typeof ConciliacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/alertas': typeof AlertasRoute
  '/bootstrap': typeof BootstrapRoute
  '/conciliacao-detalhes': typeof ConciliacaoDetalhesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/historico': typeof HistoricoRoute
  '/importacoes': typeof ImportacoesRoute
  '/importacoes-despesas': typeof ImportacoesDespesasRoute
  '/importar-os': typeof ImportarOsRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRoute
  '/patio': typeof PatioRoute
  '/proposta': typeof PropostaRoute
  '/recebiveis': typeof RecebiveisRoute
  '/conciliacao/$lojaId': typeof ConciliacaoLojaIdRoute
  '/logs/agente': typeof LogsAgenteRoute
  '/logs/motor': typeof LogsMotorRoute
  '/loja/$lojaId': typeof LojaLojaIdRoute
  '/conciliacao/': typeof ConciliacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agente'
    | '/alertas'
    | '/bootstrap'
    | '/conciliacao-detalhes'
    | '/configuracoes'
    | '/custos'
    | '/historico'
    | '/importacoes'
    | '/importacoes-despesas'
    | '/importar-os'
    | '/login'
    | '/lojas'
    | '/patio'
    | '/proposta'
    | '/recebiveis'
    | '/conciliacao/$lojaId'
    | '/logs/agente'
    | '/logs/motor'
    | '/loja/$lojaId'
    | '/conciliacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agente'
    | '/alertas'
    | '/bootstrap'
    | '/conciliacao-detalhes'
    | '/configuracoes'
    | '/custos'
    | '/historico'
    | '/importacoes'
    | '/importacoes-despesas'
    | '/importar-os'
    | '/login'
    | '/lojas'
    | '/patio'
    | '/proposta'
    | '/recebiveis'
    | '/conciliacao/$lojaId'
    | '/logs/agente'
    | '/logs/motor'
    | '/loja/$lojaId'
    | '/conciliacao'
  id:
    | '__root__'
    | '/'
    | '/agente'
    | '/alertas'
    | '/bootstrap'
    | '/conciliacao-detalhes'
    | '/configuracoes'
    | '/custos'
    | '/historico'
    | '/importacoes'
    | '/importacoes-despesas'
    | '/importar-os'
    | '/login'
    | '/lojas'
    | '/patio'
    | '/proposta'
    | '/recebiveis'
    | '/conciliacao/$lojaId'
    | '/logs/agente'
    | '/logs/motor'
    | '/loja/$lojaId'
    | '/conciliacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenteRoute: typeof AgenteRoute
  AlertasRoute: typeof AlertasRoute
  BootstrapRoute: typeof BootstrapRoute
  ConciliacaoDetalhesRoute: typeof ConciliacaoDetalhesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CustosRoute: typeof CustosRoute
  HistoricoRoute: typeof HistoricoRoute
  ImportacoesRoute: typeof ImportacoesRoute
  ImportacoesDespesasRoute: typeof ImportacoesDespesasRoute
  ImportarOsRoute: typeof ImportarOsRoute
  LoginRoute: typeof LoginRoute
  LojasRoute: typeof LojasRoute
  PatioRoute: typeof PatioRoute
  PropostaRoute: typeof PropostaRoute
  RecebiveisRoute: typeof RecebiveisRoute
  ConciliacaoLojaIdRoute: typeof ConciliacaoLojaIdRoute
  LogsAgenteRoute: typeof LogsAgenteRoute
  LogsMotorRoute: typeof LogsMotorRoute
  LojaLojaIdRoute: typeof LojaLojaIdRoute
  ConciliacaoIndexRoute: typeof ConciliacaoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recebiveis': {
      id: '/recebiveis'
      path: '/recebiveis'
      fullPath: '/recebiveis'
      preLoaderRoute: typeof RecebiveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta': {
      id: '/proposta'
      path: '/proposta'
      fullPath: '/proposta'
      preLoaderRoute: typeof PropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patio': {
      id: '/patio'
      path: '/patio'
      fullPath: '/patio'
      preLoaderRoute: typeof PatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar-os': {
      id: '/importar-os'
      path: '/importar-os'
      fullPath: '/importar-os'
      preLoaderRoute: typeof ImportarOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes-despesas': {
      id: '/importacoes-despesas'
      path: '/importacoes-despesas'
      fullPath: '/importacoes-despesas'
      preLoaderRoute: typeof ImportacoesDespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes': {
      id: '/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof ImportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos': {
      id: '/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof CustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao-detalhes': {
      id: '/conciliacao-detalhes'
      path: '/conciliacao-detalhes'
      fullPath: '/conciliacao-detalhes'
      preLoaderRoute: typeof ConciliacaoDetalhesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente': {
      id: '/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao/': {
      id: '/conciliacao/'
      path: '/conciliacao'
      fullPath: '/conciliacao/'
      preLoaderRoute: typeof ConciliacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$lojaId': {
      id: '/loja/$lojaId'
      path: '/loja/$lojaId'
      fullPath: '/loja/$lojaId'
      preLoaderRoute: typeof LojaLojaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/motor': {
      id: '/logs/motor'
      path: '/logs/motor'
      fullPath: '/logs/motor'
      preLoaderRoute: typeof LogsMotorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/agente': {
      id: '/logs/agente'
      path: '/logs/agente'
      fullPath: '/logs/agente'
      preLoaderRoute: typeof LogsAgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao/$lojaId': {
      id: '/conciliacao/$lojaId'
      path: '/conciliacao/$lojaId'
      fullPath: '/conciliacao/$lojaId'
      preLoaderRoute: typeof ConciliacaoLojaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenteRoute: AgenteRoute,
  AlertasRoute: AlertasRoute,
  BootstrapRoute: BootstrapRoute,
  ConciliacaoDetalhesRoute: ConciliacaoDetalhesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CustosRoute: CustosRoute,
  HistoricoRoute: HistoricoRoute,
  ImportacoesRoute: ImportacoesRoute,
  ImportacoesDespesasRoute: ImportacoesDespesasRoute,
  ImportarOsRoute: ImportarOsRoute,
  LoginRoute: LoginRoute,
  LojasRoute: LojasRoute,
  PatioRoute: PatioRoute,
  PropostaRoute: PropostaRoute,
  RecebiveisRoute: RecebiveisRoute,
  ConciliacaoLojaIdRoute: ConciliacaoLojaIdRoute,
  LogsAgenteRoute: LogsAgenteRoute,
  LogsMotorRoute: LogsMotorRoute,
  LojaLojaIdRoute: LojaLojaIdRoute,
  ConciliacaoIndexRoute: ConciliacaoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
